# Generated by Django 3.2.6 on 2023-02-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('direction', models.IntegerField(default=0)),
                ('requests', models.JSONField(default=list)),
            ],
        ),
    ]
